/*
 * Copyright (C) 2013 Telechips, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __ISDBT_REGION_H__
#define __ISDBT_REGION_H__

/* ==========================================================================
**  CONSTANT VARIABLE
** ========================================================================== */

#define MAX_LENGTH_OF_CHANNEL_NAME		(31)

/*   <Area_code: State Specification>
	[Remark 1] If you want to know each name matched by state ID, 
  		Refer to the table 1 in Annex F of SBTVD Standard N03.
  	[Remark 2] All of the string codes below are completed by following the ISO/IEC 8859-15. */

#define SBTVD_STATE_NUM_MAX		27

/*   <Area_code: Micro-region Specification>
	[Remark 1] If you want to know each name matched by micro-region ID (per each state ID), 
  		Refer to the document downloadable from :
  		ftp://geoftp.ibge.gov.br/Organizacao/Divisao_Territorial/2007/
  	[Remark 2] All of the string codes below are completed by following the ISO/IEC 8859-15. */

#define SBTVD_STATE01_REGION_NUM_MAX	8
#define SBTVD_STATE02_REGION_NUM_MAX	5
#define SBTVD_STATE03_REGION_NUM_MAX	13
#define SBTVD_STATE04_REGION_NUM_MAX	4
#define SBTVD_STATE05_REGION_NUM_MAX	22
#define SBTVD_STATE06_REGION_NUM_MAX	4
#define SBTVD_STATE07_REGION_NUM_MAX	8
#define SBTVD_STATE08_REGION_NUM_MAX	21
#define SBTVD_STATE09_REGION_NUM_MAX	15
#define SBTVD_STATE10_REGION_NUM_MAX	33
#define SBTVD_STATE11_REGION_NUM_MAX	19
#define SBTVD_STATE12_REGION_NUM_MAX	23
#define SBTVD_STATE13_REGION_NUM_MAX	19
#define SBTVD_STATE14_REGION_NUM_MAX	13
#define SBTVD_STATE15_REGION_NUM_MAX	13
#define SBTVD_STATE16_REGION_NUM_MAX	32
#define SBTVD_STATE17_REGION_NUM_MAX	66
#define SBTVD_STATE18_REGION_NUM_MAX	13
#define SBTVD_STATE19_REGION_NUM_MAX	18
#define SBTVD_STATE20_REGION_NUM_MAX	63
#define SBTVD_STATE21_REGION_NUM_MAX	39
#define SBTVD_STATE22_REGION_NUM_MAX	20
#define SBTVD_STATE23_REGION_NUM_MAX	35
#define SBTVD_STATE24_REGION_NUM_MAX	11
#define SBTVD_STATE25_REGION_NUM_MAX	22
#define SBTVD_STATE26_REGION_NUM_MAX	18
#define SBTVD_STATE27_REGION_NUM_MAX	1


/* ==========================================================================
**  MACRO
** ========================================================================== */

/* Because of Warnings : unsigned comparison with 0 is always true: '<=' */
#define M_CHECK_WIDE_REGION_ID(a)		((a) <= E_REGION_ID_UNDEFINED_9) // ((E_REGION_ID_UNDEFINED_0 <= (a)) && ((a) <= E_REGION_ID_UNDEFINED_9))
#define M_CHECK_WIDE_PREFECTURE_ID(a)	((E_REGION_ID_HOKKAIDO_SAPPORO <= (a)) && ((a) <= E_REGION_ID_UNDEFINED_63))


/* ==========================================================================
**  ENUMERATION
** ========================================================================== */
typedef enum
{
	E_ISDBT_FREQ_13,
	E_ISDBT_FREQ_14,
	E_ISDBT_FREQ_15,
	E_ISDBT_FREQ_16,
	E_ISDBT_FREQ_17,
	E_ISDBT_FREQ_18,
	E_ISDBT_FREQ_19,
	E_ISDBT_FREQ_20,
	E_ISDBT_FREQ_21,
	E_ISDBT_FREQ_22,
	E_ISDBT_FREQ_23,
	E_ISDBT_FREQ_24,
	E_ISDBT_FREQ_25,
	E_ISDBT_FREQ_26,
	E_ISDBT_FREQ_27,
	E_ISDBT_FREQ_28,
	E_ISDBT_FREQ_29,
	E_ISDBT_FREQ_30,
	E_ISDBT_FREQ_31,
	E_ISDBT_FREQ_32,
	E_ISDBT_FREQ_33,
	E_ISDBT_FREQ_34,
	E_ISDBT_FREQ_35,
	E_ISDBT_FREQ_36,
	E_ISDBT_FREQ_37,
	E_ISDBT_FREQ_38,
	E_ISDBT_FREQ_39,
	E_ISDBT_FREQ_40,
	E_ISDBT_FREQ_41,
	E_ISDBT_FREQ_42,
	E_ISDBT_FREQ_43,
	E_ISDBT_FREQ_44,
	E_ISDBT_FREQ_45,
	E_ISDBT_FREQ_46,
	E_ISDBT_FREQ_47,
	E_ISDBT_FREQ_48,
	E_ISDBT_FREQ_49,
	E_ISDBT_FREQ_50,
	E_ISDBT_FREQ_51,
	E_ISDBT_FREQ_52,
	E_ISDBT_FREQ_53,
	E_ISDBT_FREQ_54,
	E_ISDBT_FREQ_55,
	E_ISDBT_FREQ_56,
	E_ISDBT_FREQ_57,
	E_ISDBT_FREQ_58,
	E_ISDBT_FREQ_59,
	E_ISDBT_FREQ_60,
	E_ISDBT_FREQ_61,
	E_ISDBT_FREQ_62,
	E_ISDBT_FREQ_63,
	E_ISDBT_FREQ_64,
	E_ISDBT_FREQ_65,
	E_ISDBT_FREQ_66,
	E_ISDBT_FREQ_67,
	E_ISDBT_FREQ_68,
	E_ISDBT_FREQ_69,
	
	E_ISDBT_FREQ_MAX
} E_ISDBT_FREQ_TYPE;
#define	ISDBT_FREQ_JPN_MIN	(E_ISDBT_FREQ_13)
#define	ISDBT_FREQ_JPN_MAX	(E_ISDBT_FREQ_62)

#define	SBTVD_FREQ_BRA_MIN	(E_ISDBT_FREQ_14)
#define	SBTVD_FREQ_BRA_MAX	(E_ISDBT_FREQ_69)


typedef enum
{
	E_STR_LANG_ENGLISH,
	E_STR_LANG_JAPANESE,

	E_STR_LANG_MAX
} E_STRING_LANGUAGE_TYPE;


typedef enum
{
	E_ISDBT_STR_ID_NONE,

	/* ----------------------------------------------------------------------
	**  Region Name
	*/
	E_ISDBT_STR_ID_UNDEFINED,
	E_ISDBT_STR_ID_KANTO_WIDE_AREA,
	E_ISDBT_STR_ID_KINKI_WIDE_AREA,
	E_ISDBT_STR_ID_CHUKYO_WIDE_AREA,
	E_ISDBT_STR_ID_HOKKAIDO_AREA,
	E_ISDBT_STR_ID_OKAYAMA_N_KAGAWA,
	E_ISDBT_STR_ID_SHIMANE_N_TOTTORI,
	E_ISDBT_STR_ID_HOKKAIDO_SAPPORO,
	E_ISDBT_STR_ID_HOKKAIDO_HAKODATE,
	E_ISDBT_STR_ID_HOKKAIDO_ASAHIKAWA,
	E_ISDBT_STR_ID_HOKKAIDO_OBIHIRO,
	E_ISDBT_STR_ID_HOKKAIDO_KUSHIRO,
	E_ISDBT_STR_ID_HOKKAIDO_KITAMI,
	E_ISDBT_STR_ID_HOKKAIDO_MURORAN,
	E_ISDBT_STR_ID_MIYAGI,
	E_ISDBT_STR_ID_AKITA,
	E_ISDBT_STR_ID_YAMAGATA,
	E_ISDBT_STR_ID_IWATE,
	E_ISDBT_STR_ID_FUKUSHIMA,
	E_ISDBT_STR_ID_AOMORI,
	E_ISDBT_STR_ID_TOKYO,
	E_ISDBT_STR_ID_KANAGAWA,
	E_ISDBT_STR_ID_GUNMA,
	E_ISDBT_STR_ID_IBARAKI,
	E_ISDBT_STR_ID_CHIBA,
	E_ISDBT_STR_ID_TOCHIGI,
	E_ISDBT_STR_ID_SAITAMA,
	E_ISDBT_STR_ID_NAGANO,
	E_ISDBT_STR_ID_NIIGATA,
	E_ISDBT_STR_ID_YAMANASHI,
	E_ISDBT_STR_ID_AICHI,
	E_ISDBT_STR_ID_ISHIKAWA,
	E_ISDBT_STR_ID_SHIZUOKA,
	E_ISDBT_STR_ID_FUKUI,
	E_ISDBT_STR_ID_TOYAMA,
	E_ISDBT_STR_ID_MIE,
	E_ISDBT_STR_ID_GIFU,
	E_ISDBT_STR_ID_OSAKA,
	E_ISDBT_STR_ID_KYOTO,
	E_ISDBT_STR_ID_HYOGO,
	E_ISDBT_STR_ID_WAKAYAMA,
	E_ISDBT_STR_ID_NARA,
	E_ISDBT_STR_ID_SHIGA,
	E_ISDBT_STR_ID_HIROSHIMA,
	E_ISDBT_STR_ID_OKAYAMA,
	E_ISDBT_STR_ID_SHIMANE,
	E_ISDBT_STR_ID_TOTTORI,
	E_ISDBT_STR_ID_YAMAGUCHI,
	E_ISDBT_STR_ID_EHIME,
	E_ISDBT_STR_ID_KAGAWA,
	E_ISDBT_STR_ID_TOKUSHIMA,
	E_ISDBT_STR_ID_KOUCHI,
	E_ISDBT_STR_ID_FUKUOKA,
	E_ISDBT_STR_ID_KUMAMOTO,
	E_ISDBT_STR_ID_NAGASAKI,
	E_ISDBT_STR_ID_KAGOSHIMA,
	E_ISDBT_STR_ID_MIYAZAKI,
	E_ISDBT_STR_ID_OITA,
	E_ISDBT_STR_ID_SAGA,
	E_ISDBT_STR_ID_OKINAWA,

	/* ----------------------------------------------------------------------
	**  Broadcaster Name
	*/
	E_ISDBT_STR_ID_NHK_G,
	E_ISDBT_STR_ID_NHK_E,
	E_ISDBT_STR_ID_NIPPON_TV_BROADCASTING_NETWORK,
	//E_ISDBT_STR_ID_TBS,
	E_ISDBT_STR_ID_FUJI_TV_NETWORK_INC,
	E_ISDBT_STR_ID_TV_ASAHI_CORP,
	//E_ISDBT_STR_ID_TV_TOKYO,
	//E_ISDBT_STR_ID_THE_UNIVERSITY_OF_THE_AIR,
	E_ISDBT_STR_ID_NHK_EDUCATIONAL,
	E_ISDBT_STR_ID_MAINICHI_BROADCASTING_SYSTEM,
	E_ISDBT_STR_ID_KANSAI_TELECASTING_CORP,
	E_ISDBT_STR_ID_YOMIURI_TELECASTING_CORP,
	E_ISDBT_STR_ID_TOKAI_TV_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_CHUBU_NIPPON_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_NAGOYA_BROADCASTING_NETWORK,
	E_ISDBT_STR_ID_CHUKYU_TV_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_HOKKAIDO_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_THE_SAPPORO_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_HOKKAIDO_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_HOKKAIDO_CULTURAL_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TELEVISION_HOKKAIDO_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_NISHINIPPON_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_SETONAIKAI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_SANYO_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TV_SETOUCHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_OKAYAMA_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_SAIN_IN_CHUO_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_BROADCASTING_SYSTEM_OF_SAN_IN_INC,
	E_ISDBT_STR_ID_TOUHOKU_BROADCASTING_COMPANY,
	E_ISDBT_STR_ID_SENDAI_TELEVISION_INCORPORATED,
	E_ISDBT_STR_ID_MIYAGI_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_HIGASHINIPPON_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_AKITA_BROADCASTING_SYSTEM,
	E_ISDBT_STR_ID_AKITA_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_AKITA_ASAHI_BROADCASTING,
	E_ISDBT_STR_ID_YAMAGATA_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_YAMAGATA_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_TV_U_YAMAGATA_INC,
	E_ISDBT_STR_ID_SAKURANBO_TELEVISION_BROADCASTING_CORPORATION,
	E_ISDBT_STR_ID_IWATE_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TELEVISION_IWATE_CO_LTD,
	E_ISDBT_STR_ID_IWATE_ASAHI_TV_CO_LTD,
	E_ISDBT_STR_ID_FUKUSHIMA_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_FUKUSHIMA_CENTRAL_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_FUKUSHIMA_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TV_U_FUKUSHIMA_INC,
	E_ISDBT_STR_ID_AOMORI_BROADCASTING_CORPORATION,
	E_ISDBT_STR_ID_AOMORI_TELEVISION_BROADCASTING_CO_LTD,
	//E_ISDBT_STR_ID_ASAHI_BROADCASTING_AOMORI,
	E_ISDBT_STR_ID_TOKYO_METROPOLITAN_TELEVISION_BROADCASTING_CORP,
	E_ISDBT_STR_ID_TELEVISION_KANAGAWA_INC,
	E_ISDBT_STR_ID_GUNMA_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_CHIBA_TELEVISION_BROADCASTING_CORP,
	E_ISDBT_STR_ID_TOCHIGI_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_TELEVISION_SAITAMA_CO_LTD,
	E_ISDBT_STR_ID_TV_SHINSHU_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_ASAHI_BROADCASTINGNAGANO_CO_LTD,
	E_ISDBT_STR_ID_SHIN_ETSU_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_NAGANO_BROADCASTING_SYSTEM_INC,
	E_ISDBT_STR_ID_BROADCASTING_SYSTEM_OF_NIIGATA_INC,
	E_ISDBT_STR_ID_NIIGATA_SOGO_TELEVISION_INC,
	E_ISDBT_STR_ID_TELEVISON_NIIGATA_NETWORK_CO_LTD,
	E_ISDBT_STR_ID_THE_NIIGATA_TELEVISION_NETWORK_21_INC,
	E_ISDBT_STR_ID_YAMANASHI_BROADCASTING_SYSTEM,
	E_ISDBT_STR_ID_UHF_TELEVISION_YAMANASHI_INC,
	E_ISDBT_STR_ID_AICHI_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TV_KANAZAWA,
	E_ISDBT_STR_ID_HOKURIKU_ASAHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_HOKURIKU_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_ISHIKAWA_TV_CO_LTD,
	E_ISDBT_STR_ID_SHIZUOKA_BROADCASTING_SYSTEM,
	E_ISDBT_STR_ID_SHIZUOKA_TELECASTING_CO_LTD,
	E_ISDBT_STR_ID_SHIZUOKA_DAIICHI_TELEVISION_CORPORATION,
	//E_ISDBT_STR_ID_SHIZUOKA_ASAHI_TV,
	E_ISDBT_STR_ID_FUKUI_BROADCASTING_CORPORATION,
	E_ISDBT_STR_ID_FUKUI_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_KITANIHON_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TOYAMA_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TULIP_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_MIE_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_GIFU_BROADCASTING_SYSTEM_INC,
	E_ISDBT_STR_ID_TELEVISIO_OSAKA_INC,
	E_ISDBT_STR_ID_KYOTO_BROADCASTING_SYSTEM_COMPANY_LIMITED,
	E_ISDBT_STR_ID_TELEVISION_WAKAYAMA_CO_LTD,
	E_ISDBT_STR_ID_NARA_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_BIWAKO_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_RCC_BROADCASTING_COMPANY,
	E_ISDBT_STR_ID_HIROSHIMA_TELECASTING_CO_LTD,
	E_ISDBT_STR_ID_HIROSHIMA_HOME_TELEVISION_CO_LTD,
	E_ISDBT_STR_ID_SHINHIROSHIMA_TELECASTING_CO_LTD,
	E_ISDBT_STR_ID_YAMAGUCHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TV_YAMAGUCHI_BROADCASTING_SYSTEMS,
	E_ISDBT_STR_ID_YAMAGUCHI_ASAHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_NANKAI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_EHIME_ASAHI_TELEVISION_INC,
	E_ISDBT_STR_ID_I_TELEVISION_INC,
	E_ISDBT_STR_ID_EHIME_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_SHIKOKU_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_KOCHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TELEVISION_KOCHI_CO_LTD,
	E_ISDBT_STR_ID_KOCHI_SUN_SUN_BROADCASTING_INC,
	E_ISDBT_STR_ID_KYUSHU_ASAHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_RKB_MAINICHI_BROADCASTING_CORPORATION,
	E_ISDBT_STR_ID_FUKUOKA_BROADCASTING_SYSTEM,
	E_ISDBT_STR_ID_TVQ_KYUSHU_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_TELEVISION_NISHINIPPON_CORPORATION,
	//E_ISDBT_STR_ID_RKK_KUMAMOTO_BROADCASTING,
	E_ISDBT_STR_ID_TV_KUMAMOTO_CO_LTD,
	E_ISDBT_STR_ID_KUMAMOTO_KENMIN_TV,
	E_ISDBT_STR_ID_KUMAMOTO_ASAHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_NAGASAKI_BROADCASTING_COMPANY,
	E_ISDBT_STR_ID_K_K_TELEVISION_NAGASAKI,
	E_ISDBT_STR_ID_NAGASAKI_CULTURE_TELECASTING_CORPORATION,
	E_ISDBT_STR_ID_NAGASAKI_INTERNATIONAL_TELEVISION_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_MINAMINIHON_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_KAGOSHIMA_TELEVISION_STATION_CO_LTD,
	E_ISDBT_STR_ID_KAGOSHIMA_BROADCASTING_CORPORATION,
	E_ISDBT_STR_ID_KAGOSHIMA_YOMIURI_TELEVISION,
	E_ISDBT_STR_ID_MIYAZAKI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_MIYAZAKI_TELECASTING_CO_LTD,
	E_ISDBT_STR_ID_OITA_BROADCASTING_SYSTEM_INC,
	E_ISDBT_STR_ID_TELEVISION_OITA_SYSTEM,
	E_ISDBT_STR_ID_OITA_ASAHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_SAGA_TELEVISION_STATION_CO_LTD,
	E_ISDBT_STR_ID_RYUKYU_BROADCASTING_CORPORATION,
	E_ISDBT_STR_ID_RYUKYU_ASAHI_BROADCASTING_CO_LTD,
	E_ISDBT_STR_ID_OKINAWA_TELEVISION_BROADCASTING_CO_LTD,

	/* ----------------------------------------------------------------------
	**  TS Name (Full-width within 10 characters)
	*/
	E_ISDBT_STR_ID_NHK_G_TOKYO,
	E_ISDBT_STR_ID_NHK_E_TOKYO,
	E_ISDBT_STR_ID_NIPPON_TV,
	E_ISDBT_STR_ID_TBS,
	E_ISDBT_STR_ID_FUJI_TV,
	E_ISDBT_STR_ID_TV_ASAHI,
	E_ISDBT_STR_ID_TV_TOKYO,
	E_ISDBT_STR_ID_THE_UNIVERSITY_OF_THE_AIR,
	E_ISDBT_STR_ID_NHK_E_OSAKA,
	E_ISDBT_STR_ID_MBS_MAINICHI_BROADCASTING,
	E_ISDBT_STR_ID_ABC_TELEVISION,
	E_ISDBT_STR_ID_KANSAI_TELECASTING,
	E_ISDBT_STR_ID_YOMIURI_TELECASTING,
	E_ISDBT_STR_ID_NHK_E_NAGOYA,
	E_ISDBT_STR_ID_TOKAI_TV,
	E_ISDBT_STR_ID_CBC,
	E_ISDBT_STR_ID_MEE_TELE,
	E_ISDBT_STR_ID_CHUKYO_TV,
	E_ISDBT_STR_ID_HBC_HOKKAIDO_BROADCASTING,
	E_ISDBT_STR_ID_STV_SAPPORO_TELEVISION,
	E_ISDBT_STR_ID_HTB_HOKKAIDO_TELEVISION,
	E_ISDBT_STR_ID_UHB,
	E_ISDBT_STR_ID_TVH,
	E_ISDBT_STR_ID_RNC_NISHINIPPON_TELEVISION,
	E_ISDBT_STR_ID_KSB_SETONAIKAI_BROADCASTING,
	E_ISDBT_STR_ID_RSK_TELEVISION,
	E_ISDBT_STR_ID_TELEVISION_SETOUCHI,
	E_ISDBT_STR_ID_OHK_TV,
	E_ISDBT_STR_ID_SAN_IN_CHUO_TELEVISION,
	E_ISDBT_STR_ID_BSS_TELEVISION,
	E_ISDBT_STR_ID_NIHONKAI_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_SAPPORO,
	E_ISDBT_STR_ID_NHK_E_SAPPORO,
	E_ISDBT_STR_ID_HBC_SAPPORO,
	E_ISDBT_STR_ID_STV_SAPPORO,
	E_ISDBT_STR_ID_HTB_SAPPORO,
	E_ISDBT_STR_ID_UHB_SAPPORO,
	E_ISDBT_STR_ID_TVH_SAPPORO,
	E_ISDBT_STR_ID_NHK_G_HAKODATE,
	E_ISDBT_STR_ID_NHK_E_HAKODATE,
	E_ISDBT_STR_ID_HBC_HAKODATE,
	E_ISDBT_STR_ID_STV_HAKODATE,
	E_ISDBT_STR_ID_HTB_HAKODATE,
	E_ISDBT_STR_ID_UHB_HAKODATE,
	E_ISDBT_STR_ID_TVH_HAKODATE,
	E_ISDBT_STR_ID_NHK_G_ASAHIKAWA,
	E_ISDBT_STR_ID_NHK_E_ASAHIKAWA,
	E_ISDBT_STR_ID_HBC_ASAHIKAWA,
	E_ISDBT_STR_ID_STV_ASAHIKAWA,
	E_ISDBT_STR_ID_HTB_ASAHIKAWA,
	E_ISDBT_STR_ID_UHB_ASAHIKAWA,
	E_ISDBT_STR_ID_TVH_ASAHIKAWA,
	E_ISDBT_STR_ID_NHK_G_OBIHIRO,
	E_ISDBT_STR_ID_NHK_E_OBIHIRO,
	E_ISDBT_STR_ID_HBC_OBIHIRO,
	E_ISDBT_STR_ID_STV_OBIHIRO,
	E_ISDBT_STR_ID_HTB_OBIHIRO,
	E_ISDBT_STR_ID_UHB_OBIHIRO,
	E_ISDBT_STR_ID_TVH_OBIHIRO,
	E_ISDBT_STR_ID_NHK_G_KUSHIRO,
	E_ISDBT_STR_ID_NHK_E_KUSHIRO,
	E_ISDBT_STR_ID_HBC_KUSHIRO,
	E_ISDBT_STR_ID_STV_KUSHIRO,
	E_ISDBT_STR_ID_HTB_KUSHIRO,
	E_ISDBT_STR_ID_UHB_KUSHIRO,
	E_ISDBT_STR_ID_TVH_KUSHIRO,
	E_ISDBT_STR_ID_NHK_G_KITAMI,
	E_ISDBT_STR_ID_NHK_E_KITAMI,
	E_ISDBT_STR_ID_HBC_KITAMI,
	E_ISDBT_STR_ID_STV_KITAMI,
	E_ISDBT_STR_ID_HTB_KITAMI,
	E_ISDBT_STR_ID_UHB_KITAMI,
	E_ISDBT_STR_ID_TVH_KITAMI,
	E_ISDBT_STR_ID_NHK_G_MURORAN,
	E_ISDBT_STR_ID_NHK_E_MURORAN,
	E_ISDBT_STR_ID_HBC_MURORAN,
	E_ISDBT_STR_ID_STV_MURORAN,
	E_ISDBT_STR_ID_HTB_MURORAN,
	E_ISDBT_STR_ID_UHB_MURORAN,
	E_ISDBT_STR_ID_TVH_MURORAN,
	E_ISDBT_STR_ID_NHK_G_SENDAI,
	E_ISDBT_STR_ID_NHK_E_SENDAI,
	E_ISDBT_STR_ID_TBC_TELEVISION,
	E_ISDBT_STR_ID_SENDAI_TELEVISION,
	E_ISDBT_STR_ID_MIYAGI_TELEVISION,
	E_ISDBT_STR_ID_KHB_HIGASHINIPPON_BROADCASTING,
	E_ISDBT_STR_ID_NHK_G_AKITA,
	E_ISDBT_STR_ID_NHK_E_AKITA,
	E_ISDBT_STR_ID_ABS_AKITA_BROADCASTING,
	E_ISDBT_STR_ID_AKT_AKITA_TELEVISION,
	E_ISDBT_STR_ID_AAB_AKITA_ASAHI_BROADCASTING,
	E_ISDBT_STR_ID_NHK_G_YAMAGATA,
	E_ISDBT_STR_ID_NHK_E_YAMAGATA,
	E_ISDBT_STR_ID_YBC_YAMAGATA_BROADCASTING,
	E_ISDBT_STR_ID_YTS_YAMAGATA_TELEVISION,
	E_ISDBT_STR_ID_TV_U_YAMAGATA,
	E_ISDBT_STR_ID_SAKURANBO_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_MORIOKA,
	E_ISDBT_STR_ID_NHK_E_MORIOKA,
	E_ISDBT_STR_ID_IBC_TELEVISION,
	E_ISDBT_STR_ID_TELEVISION_IWATE,
	E_ISDBT_STR_ID_MENKOI_TELEVISION,
	E_ISDBT_STR_ID_IWATE_ASAHI_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_FUKUSHIMA,
	E_ISDBT_STR_ID_NHK_E_FUKUSHIMA,
	E_ISDBT_STR_ID_FUKUSHIMA_TELEVISION,
	E_ISDBT_STR_ID_FUKUSHIMA_CENTRAL_TELEVISIO,
	E_ISDBT_STR_ID_KFB_FUKUSHIMA_BROADCASTING,
	E_ISDBT_STR_ID_TV_U_FUKUSHIMA,
	E_ISDBT_STR_ID_NHK_G_AOMORI,
	E_ISDBT_STR_ID_NHK_E_AOMORI,
	E_ISDBT_STR_ID_RAB_AOMORI_BROADCASTING,
	E_ISDBT_STR_ID_ATV_AOMORI_TELEVISION,
	E_ISDBT_STR_ID_ASAHI_BROADCASTING_AOMORI,
	E_ISDBT_STR_ID_TOKYO_MX_TELEVISION,
	E_ISDBT_STR_ID_TVK,
	E_ISDBT_STR_ID_GUNMA_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_MITO,
	E_ISDBT_STR_ID_CHIBA_TELEVISION,
	E_ISDBT_STR_ID_TOCHIGI_TELEVISION,
	E_ISDBT_STR_ID_TELETAMA,
	E_ISDBT_STR_ID_NHK_G_NAGANO,
	E_ISDBT_STR_ID_NHK_E_NAGANO,
	E_ISDBT_STR_ID_TV_SHINSHU,
	E_ISDBT_STR_ID_ABN_ASAHI_BROADCASTING_NAGANO,
	E_ISDBT_STR_ID_SBC_SHIN_ETSU_BROADCASTING,
	E_ISDBT_STR_ID_NBS_NAGANO_BROADCASTING,
	E_ISDBT_STR_ID_NHK_G_NIIGATA,
	E_ISDBT_STR_ID_NHK_E_NIIGATA,
	E_ISDBT_STR_ID_BSN,
	E_ISDBT_STR_ID_NST,
	E_ISDBT_STR_ID_TENY_TELEVISION_NIIGATA,
	E_ISDBT_STR_ID_NIIGATA_TELEVISION_21,
	E_ISDBT_STR_ID_NHK_G_KOFU,
	E_ISDBT_STR_ID_NHK_E_KOFU,
	E_ISDBT_STR_ID_YBS_YAMANASHI_BROADCASTING,
	E_ISDBT_STR_ID_UTY,
	E_ISDBT_STR_ID_NHK_G_NAGOYA,
	E_ISDBT_STR_ID_AICHI_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_KANAZAWA,
	E_ISDBT_STR_ID_NHK_E_KANAZAWA,
	E_ISDBT_STR_ID_TVKANAZAWA,
	E_ISDBT_STR_ID_HOKURIKU_ASAHI_BROADCASTING,
	E_ISDBT_STR_ID_MRO,
	E_ISDBT_STR_ID_ISHIKAWA_TV,
	E_ISDBT_STR_ID_NHK_G_SHIZUOKA,
	E_ISDBT_STR_ID_NHK_E_SHIZUOKA,
	E_ISDBT_STR_ID_SBS,
	E_ISDBT_STR_ID_SHIZUOKA_TELECASTING,
	E_ISDBT_STR_ID_SHIZUOKA_DAIICHI_TELEVISIN,
	E_ISDBT_STR_ID_SHIZUOKA_ASAHI_TV,
	E_ISDBT_STR_ID_NHK_G_FUKUI,
	E_ISDBT_STR_ID_NHK_E_FUKUI,
	E_ISDBT_STR_ID_FBC_TELEVISION,
	E_ISDBT_STR_ID_FUKUI_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_TOYAMA,
	E_ISDBT_STR_ID_NHK_E_TOYAMA,
	E_ISDBT_STR_ID_KNB_KITANIHON_BROADCASTING,
	E_ISDBT_STR_ID_BBT_TOYAMA_TELEVISION,
	E_ISDBT_STR_ID_TULIP_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_TSU,
	E_ISDBT_STR_ID_MIE_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_GIFU,
	E_ISDBT_STR_ID_GIFU_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_OSAKA,
	E_ISDBT_STR_ID_TELEVISION_OSAKA,
	E_ISDBT_STR_ID_NHK_G_KYOTO,
	E_ISDBT_STR_ID_KBS_KYOTO,
	E_ISDBT_STR_ID_NHK_G_KOBE,
	E_ISDBT_STR_ID_SUN_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_WAKAYAMA,
	E_ISDBT_STR_ID_TELEVISION_WAKAYAMA,
	E_ISDBT_STR_ID_NHK_G_NARA,
	E_ISDBT_STR_ID_NARA_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_OTSU,
	E_ISDBT_STR_ID_BBC_BIWAKO_BROADCASTING,
	E_ISDBT_STR_ID_NHK_G_HIROSHIMA,
	E_ISDBT_STR_ID_NHK_E_HIROSHIMA,
	E_ISDBT_STR_ID_RCC_TELEVISION,
	E_ISDBT_STR_ID_HIROSHIMA_TELEVISION,
	E_ISDBT_STR_ID_HIROSHIMA_HOME_TELEVISION,
	E_ISDBT_STR_ID_TSS,
	E_ISDBT_STR_ID_NHK_G_OKAYAMA,
	E_ISDBT_STR_ID_NHK_E_OKAYAMA,
	E_ISDBT_STR_ID_NHK_G_MATSUE,
	E_ISDBT_STR_ID_NHK_E_MATSUE,
	E_ISDBT_STR_ID_NHK_G_TOTTORI,
	E_ISDBT_STR_ID_NHK_E_TOTTORI,
	E_ISDBT_STR_ID_NHK_G_YAMAGUCHI,
	E_ISDBT_STR_ID_NHK_E_YAMAGUCHI,
	E_ISDBT_STR_ID_KRY_YAMAGUCHI_BROADCASTING,
	E_ISDBT_STR_ID_TYS_TV_YAMAGUCHI,
	E_ISDBT_STR_ID_YAB_YAMAGUCHI_ASAHI,
	E_ISDBT_STR_ID_NHK_G_MATSUYAMA,
	E_ISDBT_STR_ID_NHK_E_MATSUYAMA,
	E_ISDBT_STR_ID_NANKAI_BROADCASTING,
	E_ISDBT_STR_ID_EHIME_ASAHI_TELEVISION,
	E_ISDBT_STR_ID_I_TELEVISION,
	E_ISDBT_STR_ID_TELEVISION_EHIME,
	E_ISDBT_STR_ID_NHK_G_TAKAMATSU,
	E_ISDBT_STR_ID_NHK_E_TAKAMATSU,
	E_ISDBT_STR_ID_NHK_G_TOKUSHIMA,
	E_ISDBT_STR_ID_NHK_E_TOKUSHIMA,
	E_ISDBT_STR_ID_SHIKOKU_BROADCATING,
	E_ISDBT_STR_ID_NHK_G_KOUCHI,
	E_ISDBT_STR_ID_NHK_E_KOUCHI,
	E_ISDBT_STR_ID_KOCHI_BROADCASTING,
	E_ISDBT_STR_ID_TELEVISION_KOCHI,
	E_ISDBT_STR_ID_SUN_SUN_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_FUKUOKA,
	E_ISDBT_STR_ID_NHK_G_KITAKYUSHU,
	E_ISDBT_STR_ID_NHK_E_FUKUOKA,
	E_ISDBT_STR_ID_NHK_E_KITAKYUSHU,
	E_ISDBT_STR_ID_KBC_KYUSHU_ASAHI_BROADCASTING,
	E_ISDBT_STR_ID_RKB_MAINICHI_BROADCASTING,
	E_ISDBT_STR_ID_FBS_FUKUOKA_BROADCASTING,
	E_ISDBT_STR_ID_TVQ_KYUSHU_BROADCASTING,
	E_ISDBT_STR_ID_TNC_TELEVISION_NISHINIPPON,
	E_ISDBT_STR_ID_NHK_G_KUMAMOTO,
	E_ISDBT_STR_ID_NHK_E_KUMAMOTO,
	E_ISDBT_STR_ID_RKK_KUMAMOTO_BROADCASTING,
	E_ISDBT_STR_ID_TKU_TV_KUMAMOTO,
	E_ISDBT_STR_ID_KKT_KUMAMATO_KENMIN,
	E_ISDBT_STR_ID_KAB_KUMAMOTO_ASAHI_BROADCASTING,
	E_ISDBT_STR_ID_NHK_G_NAGASAKI,
	E_ISDBT_STR_ID_NHK_E_NAGASAKI,
	E_ISDBT_STR_ID_NBC_NAGASAKI_BROADCASTING,
	E_ISDBT_STR_ID_KTN_TELEVISION_NAGASAKI,
	E_ISDBT_STR_ID_NCC_NAGASAKI_CULTURE_TELECASTING,
	E_ISDBT_STR_ID_NIB_NAGASAKI_INTERNATIONAL_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_KAGOSHIMA,
	E_ISDBT_STR_ID_NHK_E_KAGOSHIMA,
	E_ISDBT_STR_ID_MBC_MINAMINIHON_BROADCASTING,
	E_ISDBT_STR_ID_KTS_KAGOSHIMA_TELEVISION,
	E_ISDBT_STR_ID_KKB_KAGOSHIMA_BROADCASTING,
	E_ISDBT_STR_ID_KYT_KAGOSHIMA_YOMIURI_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_MIYAZAKI,
	E_ISDBT_STR_ID_NHK_E_MIYAZAKI,
	E_ISDBT_STR_ID_MRT_MIYAZAKI_BROADCASTING,
	E_ISDBT_STR_ID_UMK_MIYAZAKI_TELECASTING,
	E_ISDBT_STR_ID_NHK_G_OITA,
	E_ISDBT_STR_ID_NHK_E_OITA,
	E_ISDBT_STR_ID_OBS_OITA_BROADCASTING,
	E_ISDBT_STR_ID_TOS_TELEVISION_OITA,
	E_ISDBT_STR_ID_OAB_OITA_ASAHI_BROADCASTING,
	E_ISDBT_STR_ID_NHK_G_SAGA,
	E_ISDBT_STR_ID_NHK_E_SAGA,
	E_ISDBT_STR_ID_STS_SAGA_TELEVISION,
	E_ISDBT_STR_ID_NHK_G_NAHA,
	E_ISDBT_STR_ID_NHK_E_NAHA,
	E_ISDBT_STR_ID_RBC_RYUKYU_BROADCASTING,
	E_ISDBT_STR_ID_QAB_RYUKYU_ASAHI_BROADCASTING,
	E_ISDBT_STR_ID_OKINAWA_TELEVISION_OTV,

	E_ISDBT_STR_ID_LAST,

	E_ISDBT_STR_ID_MAX
} E_ISDBT_STRING_ID;


typedef enum
{
	E_REGION_ID_UNDEFINED_0,
	E_REGION_ID_KANTO_WIDE_AREA,
	E_REGION_ID_KINKI_WIDE_AREA,
	E_REGION_ID_CHUKYO_WIDE_AREA,
	E_REGION_ID_HOKKAIDO_AREA,
	E_REGION_ID_OKAYAMA_N_KAGAWA,
	E_REGION_ID_SHIMANE_N_TOTTORI,
	E_REGION_ID_UNDEFINED_7,
	E_REGION_ID_UNDEFINED_8,
	E_REGION_ID_UNDEFINED_9,
	/* ------------------------------ */

	E_REGION_ID_HOKKAIDO_SAPPORO,	// 10
	E_REGION_ID_HOKKAIDO_HAKODATE,
	E_REGION_ID_HOKKAIDO_ASAHIKAWA,
	E_REGION_ID_HOKKAIDO_OBIHIRO,
	E_REGION_ID_HOKKAIDO_KUSHIRO,
	E_REGION_ID_HOKKAIDO_KITAMI,
	E_REGION_ID_HOKKAIDO_MURORAN,
	E_REGION_ID_MIYAGI,
	E_REGION_ID_AKITA,
	E_REGION_ID_YAMAGATA,
	E_REGION_ID_IWATE,				// 20
	E_REGION_ID_FUKUSHIMA,
	E_REGION_ID_AOMORI,
	E_REGION_ID_TOKYO,
	E_REGION_ID_KANAGAWA,
	E_REGION_ID_GUNMA,
	E_REGION_ID_IBARAKI,
	E_REGION_ID_CHIBA,
	E_REGION_ID_TOCHIGI,
	E_REGION_ID_SAITAMA,
	E_REGION_ID_NAGANO,				// 30
	E_REGION_ID_NIIGATA,
	E_REGION_ID_YAMANASHI,
	E_REGION_ID_AICHI,
	E_REGION_ID_ISHIKAWA,
	E_REGION_ID_SHIZUOKA,
	E_REGION_ID_FUKUI,
	E_REGION_ID_TOYAMA,
	E_REGION_ID_MIE,
	E_REGION_ID_GIFU,
	E_REGION_ID_OSAKA,				// 40
	E_REGION_ID_KYOTO,
	E_REGION_ID_HYOGO,
	E_REGION_ID_WAKAYAMA,
	E_REGION_ID_NARA,
	E_REGION_ID_SHIGA,
	E_REGION_ID_HIROSHIMA,
	E_REGION_ID_OKAYAMA,
	E_REGION_ID_SHIMANE,
	E_REGION_ID_TOTTORI,
	E_REGION_ID_YAMAGUCHI,			// 50
	E_REGION_ID_EHIME,
	E_REGION_ID_KAGAWA,
	E_REGION_ID_TOKUSHIMA,
	E_REGION_ID_KOUCHI,
	E_REGION_ID_FUKUOKA,
	E_REGION_ID_KUMAMOTO,
	E_REGION_ID_NAGASAKI,
	E_REGION_ID_KAGOSHIMA,
	E_REGION_ID_MIYAZAKI,
	E_REGION_ID_OITA,				// 60
	E_REGION_ID_SAGA,
	E_REGION_ID_OKINAWA,
	E_REGION_ID_UNDEFINED_63,

	E_REGION_ID_MAX
} E_ASSIGNMENT_REGION_ID;

#define REGION_ID_SETTING_BEGIN			(E_REGION_ID_HOKKAIDO_SAPPORO)
#define REGION_ID_SETTING_END			(E_REGION_ID_OKINAWA)


typedef enum
{
	E_REGION_HOKKAIDO_SAPPORO,
	E_REGION_HOKKAIDO_HAKODATE,
	E_REGION_HOKKAIDO_ASAHIKAWA,
	E_REGION_HOKKAIDO_OBIHIRO,
	E_REGION_HOKKAIDO_KUSHIRO,
	E_REGION_HOKKAIDO_KITAMI,
	E_REGION_HOKKAIDO_MURORAN,
	E_REGION_MIYAGI,
	E_REGION_AKITA,
	E_REGION_YAMAGATA,
	E_REGION_IWATE,
	E_REGION_FUKUSHIMA,
	E_REGION_AOMORI,
	E_REGION_TOKYO,
	E_REGION_KANAGAWA,
	E_REGION_GUNMA,
	E_REGION_IBARAKI,
	E_REGION_CHIBA,
	E_REGION_TOCHIGI,
	E_REGION_SAITAMA,
	E_REGION_NAGANO,
	E_REGION_NIIGATA,
	E_REGION_YAMANASHI,
	E_REGION_AICHI,
	E_REGION_ISHIKAWA,
	E_REGION_SHIZUOKA,
	E_REGION_FUKUI,
	E_REGION_TOYAMA,
	E_REGION_MIE,
	E_REGION_GIFU,
	E_REGION_OSAKA,
	E_REGION_KYOTO,
	E_REGION_HYOGO,
	E_REGION_WAKAYAMA,
	E_REGION_NARA,
	E_REGION_SHIGA,
	E_REGION_HIROSHIMA,
	E_REGION_OKAYAMA,
	E_REGION_SHIMANE,
	E_REGION_TOTTORI,
	E_REGION_YAMAGUCHI,
	E_REGION_EHIME,
	E_REGION_KAGAWA,
	E_REGION_TOKUSHIMA,
	E_REGION_KOUCHI,
	E_REGION_FUKUOKA,
	E_REGION_KUMAMOTO,
	E_REGION_NAGASAKI,
	E_REGION_KAGOSHIMA,
	E_REGION_MIYAZAKI,
	E_REGION_OITA,
	E_REGION_SAGA,
	E_REGION_OKINAWA,

	E_REGION_MAX
} E_REGION_TYPE;

/* --------------------------------------------------
**  Number of Preset
** -------------------------------------------------- */
typedef enum
{
	E_PRESET_LIST_1ST,
//	E_PRESET_LIST_2ND,
//	E_PRESET_LIST_3RD,

	E_PRESET_LIST_MAX
} E_PRESET_LIST;

/* --------------------------------------------------
**  Preset Channel Item Numebr
** -------------------------------------------------- */
typedef enum
{
	E_PRESET_CHANNEL_ITEM_1ST,
	E_PRESET_CHANNEL_ITEM_2ND,
	E_PRESET_CHANNEL_ITEM_3RD,
	E_PRESET_CHANNEL_ITEM_4TH,
	E_PRESET_CHANNEL_ITEM_5TH,
	E_PRESET_CHANNEL_ITEM_6TH,
	E_PRESET_CHANNEL_ITEM_7TH,
	E_PRESET_CHANNEL_ITEM_8TH,
	E_PRESET_CHANNEL_ITEM_9TH,
	E_PRESET_CHANNEL_ITEM_10TH,
	E_PRESET_CHANNEL_ITEM_11TH,
	E_PRESET_CHANNEL_ITEM_12TH,
	E_PRESET_CHANNEL_ITEM_13TH,
	E_PRESET_CHANNEL_ITEM_14TH,
	E_PRESET_CHANNEL_ITEM_15TH,
	E_PRESET_CHANNEL_ITEM_16TH,
	E_PRESET_CHANNEL_ITEM_17TH,
	E_PRESET_CHANNEL_ITEM_18TH,
	E_PRESET_CHANNEL_ITEM_19TH,
	E_PRESET_CHANNEL_ITEM_20TH,
	E_PRESET_CHANNEL_ITEM_21TH,
	E_PRESET_CHANNEL_ITEM_22TH,
	E_PRESET_CHANNEL_ITEM_23TH,
	E_PRESET_CHANNEL_ITEM_24TH,

	E_PRESET_CHANNEL_ITEM_MAX
} E_PRESET_CHANNEL_ITEM;

/* ==========================================================================
**  STRUCTURE
** ========================================================================== */

typedef unsigned int	U32_STRING_ID;

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**  REGION
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* --------------------------------------------------
**  String Information Structure
** -------------------------------------------------- */
typedef struct
{
	U32_STRING_ID		string_id;
	unsigned char		*p_string_data[E_STR_LANG_MAX];
} T_STRING_INFO;

typedef struct
{
	unsigned char * 	stateName;
	unsigned char ** 	regionNamePool;
	unsigned char		maxPoolNum;
} SBTVD_AREACODE_STRPOOL;

/* --------------------------------------------------
**  Boradcaster Information Structure
** -------------------------------------------------- */
typedef struct
{
	unsigned char		broadcaster_id;
	U32_STRING_ID		broadcaster_name_str_id;
	unsigned short		transport_stream_id;
	U32_STRING_ID		ts_name_str_id;
	unsigned char		remote_control_key_id;
	unsigned short		min_service_id;
	unsigned short		max_service_id;
} T_BROADCASTER_INFO;


/* --------------------------------------------------
**  Region ID Information Structure
** -------------------------------------------------- */
typedef struct
{
	U32_STRING_ID		region_name_str_id;
	unsigned char		region_id;
	T_BROADCASTER_INFO	*pst_broadcaster_list;
	int					broadcaster_list_nums;
} T_REGION_ID_INFO;


/* --------------------------------------------------
**  Channel Information Structure
** -------------------------------------------------- */
typedef struct
{
	unsigned char		region_id;
	unsigned char		remote_control_key_id;
	unsigned char		channel_frequency_index;
} T_CHANNEL_INFO;


/* --------------------------------------------------
**  Region Information Structure
** -------------------------------------------------- */
typedef struct
{
	U32_STRING_ID		region_name_str_id;
	T_CHANNEL_INFO		*pst_channel_list;
	int					channel_list_nums;
} T_REGION_INFO;


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**  PRESET
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* --------------------------------------------------
**  Channel Information Structure for Preset
** -------------------------------------------------- */
typedef struct
{
	unsigned char		region_id;
	unsigned short		transport_stream_id;
	unsigned short		service_id;
#ifdef ISDBT_DETECT_EXT_SERVICE_ID
	unsigned short		ext_service_id;
#endif
	unsigned char		chName[MAX_LENGTH_OF_CHANNEL_NAME];
	unsigned char		remote_control_key_id;
	unsigned char		chFreqIdx;
	unsigned short	areaCode;
} T_PRESET_CHANNEL_INFO, *P_PRESET_CHANNEL_INFO;


/* --------------------------------------------------
**  Preset Information Structure
** -------------------------------------------------- */
typedef struct
{
	unsigned char			wide_region_id;
	unsigned char			prefecture_region_id;
	unsigned char			preset_name[MAX_LENGTH_OF_CHANNEL_NAME];
	T_PRESET_CHANNEL_INFO	channel_info[E_PRESET_CHANNEL_ITEM_MAX];
} T_PRESET_LIST_INFO;


/* --------------------------------------------------
**  Preset Information Structure
** -------------------------------------------------- */
typedef struct
{
	unsigned char		cur_preset_idx;
	unsigned char		cur_channel_index;
	T_PRESET_LIST_INFO	preset_list_info[E_PRESET_LIST_MAX];
} T_PRESET_INFO;

/* ==========================================================================
**  GLOBAL VARIABLE
** ========================================================================== */

extern const T_REGION_ID_INFO stISDBT_RegionID_Info[E_REGION_ID_MAX];
extern const T_REGION_INFO stISDBT_RegionInfo[E_REGION_MAX];
extern T_PRESET_INFO stISDBT_PresetInfo;


/* ==========================================================================
**  GLOBAL FUNCTION
** ========================================================================== */

/**************************************************************************
*  
*  FUNCTION NAME
*      int ISDBT_Set_StringLanguage(unsigned char uiStrLengType);
*  
*  DESCRIPTION 
*      This function sets the string lenguage type.
*  
*  INPUT
*      uiStrLengType = String lenguage type.
*  
*  OUTPUT
*      int = Return type.
*  
*  REMARK
*      None
**************************************************************************/
extern int ISDBT_Set_StringLanguage(unsigned char uiStrLengType);


/**************************************************************************
*  
*  FUNCTION NAME
*      unsigned char ISDBT_Get_StringLanguage(void);
*  
*  DESCRIPTION 
*      This function returns the current string lenguage type.
*  
*  INPUT
*      None
*  
*  OUTPUT
*      unsigned char = Current string lenguage type.
*  
*  REMARK
*      None
**************************************************************************/
extern unsigned char ISDBT_Get_StringLanguage(void);


/**************************************************************************
*  
*  FUNCTION NAME
*      unsigned char *ISDBT_Get_String(U32_STRING_ID str_id);
*  
*  DESCRIPTION 
*      This function returns the pointer of string according to input string ID.
*  
*  INPUT
*      str_id = String ID
*  
*  OUTPUT
*      unsigned char * - Pointer of string searched.
*  
*  REMARK
*      None
**************************************************************************/
extern unsigned char *ISDBT_Get_String(U32_STRING_ID str_id);


extern int ISDBT_Init_PresetChannelList(unsigned char PresetIndex);
extern int ISDBT_Init_CurPresetChannelList(void);
extern int ISDBT_Init_PresetInfo(unsigned char PresetIndex);
extern int ISDBT_Init_CurPresetInfo(void);
extern void ISDBT_Init_AllPresetInfo(int country_code);
extern unsigned char ISDBT_Get_CurPresetIndex(void);
extern int ISDBT_Set_CurPresetIndex(unsigned char PresetIndex);
extern unsigned char ISDBT_Get_PresetWideRegionID(unsigned char PresetIndex);
extern unsigned char ISDBT_Get_CurPresetWideRegionID(void);
extern unsigned char ISDBT_Get_PresetPrefectureRegionID(unsigned char PresetIndex);
extern unsigned char ISDBT_Get_CurPresetPrefectureRegionID(void);
extern int ISDBT_Set_PresetChannelListByRegion(unsigned char PresetIndex, unsigned char Region);
extern int ISDBT_Set_CurPresetChannelListByRegion(int area_code);
extern unsigned char ISDBT_Get_ChannelFrequencyIndex(unsigned char PresetIndex, unsigned char channel_index);
extern unsigned char ISDBT_Get_CurChannelFrequencyIndex(unsigned char channel_index);
extern T_PRESET_CHANNEL_INFO *ISDBT_Get_ChannelListInfo(unsigned char PresetIndex, unsigned char channel_index);
extern T_PRESET_CHANNEL_INFO *ISDBT_Get_CurChannelListInfo(unsigned char channel_index);
extern int ISDBT_Set_ChannelInfo(unsigned char channel_index, T_PRESET_CHANNEL_INFO *pstChInfo);
extern unsigned char ISDBT_Get_CurrentChannelIndex(void);
extern int ISDBT_Set_CurrentChannelIndex(unsigned char CurChIdx);
extern unsigned char ISDBT_Get_FirstPlayChannelIndex(void);
extern unsigned char ISDBT_Get_NextPlayChannelIndex(void);
extern unsigned char ISDBT_Get_PrevPlayChannelIndex(void);
extern int ISDBT_Get_ValidChannelNums(void);

#ifdef DxB_SBTVD_INCLUDE
extern unsigned short ISDBT_Get_ChannelAreaCode(unsigned char PresetIndex, unsigned char channel_index);
extern unsigned short ISDBT_Get_CurChannelAreaCode(unsigned char channel_index);
extern SBTVD_AREACODE_STRPOOL * SBTVD_GetAreaStrPoolPtr(void);
extern unsigned char SBTVD_GetChannelStateID(unsigned short Areacode);
extern unsigned short SBTVD_GetChannelMicroRegionID(unsigned short Areacode);
extern unsigned char SBTVD_GetChannelMaxRegionNum(unsigned char StateID);
extern unsigned char SBTVD_GetRegionTableID(unsigned char StateID, unsigned short MicroRegionID);
#endif	// DxB_SBTVD_INCLUDE

extern int ISDBT_Get_TotalChNum_from_RegionInfo(int region);
extern int ISDBT_Get_FreqIndex_from_RegionInfo(int index, int region);
extern unsigned char *ISDBT_Get_CurChannelNameIndex (unsigned char channel_index);
extern unsigned char ISDBT_Get_CurChannelRemoconIDIndex (unsigned char channel_index);
extern unsigned short ISDBT_Get_CurTStreamIDIndex (unsigned char channel_index);

#endif /* __ISDBT_REGION_H__ */

