obj-m := tcc_dxb_drv.o
tcc_dxb_drv-objs := tcc_dxb_kernel.o tcc_fe.o tcc_tuner.o tcc_tsif_interface.o tcc_dmx.o

DESC_CFLAGS += -I$/MxL101/include
obj-m += MxL101/

DESC_CFLAGS += -I$/AVL6211/include
obj-m += AVL6211/

DESC_CFLAGS += -I$/MN88472/common
DESC_CFLAGS += -I$/MN88472/mn88472
obj-m += MN88472/

