# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_GPIO_TCC)	+= switch_gpio_tcc.o
obj-$(CONFIG_SWITCH_GPIO_HDMI)	+= switch_gpio_hdmi.o

