obj-m += mxl101_fe.o 

mxl101_fe-objs := mxlfrontend.o

mxl101_fe-objs += src/demod_MxL101SF.o \
                  src/MxL101SF_OEM_Drv.o \
                  src/MxL101SF_PhyCfg.o \
                  src/MxL101SF_PhyCtrlApi.o
