LOCAL_PATH:= $(call my-dir)

ifeq ($(TARGET_SPLASH_USE),true)

include $(CLEAR_VARS)
LOCAL_MODULE := mksplash
LOCAL_SRC_FILES := mksplash.c
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_SUFFIX :=
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := $(notdir $(LOCAL_SRC_FILES))
LOCAL_IS_HOST_MODULE := true
include $(BUILD_HOST_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_MODULE := rgbto888
LOCAL_SRC_FILES:= to888.c
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_SUFFIX :=
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := $(notdir $(LOCAL_SRC_FILES))
LOCAL_IS_HOST_MODULE := true
include $(BUILD_HOST_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_MODULE := mksplashimg
LOCAL_SRC_FILES:= mksplashimg.sh
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_SUFFIX :=
LOCAL_MODULE_TAGS := optional
LOCAL_BUILT_MODULE_STEM := $(notdir $(LOCAL_SRC_FILES))
LOCAL_IS_HOST_MODULE := true
include $(BUILD_PREBUILT)


$(call dist-for-goals,dist_files,$(LOCAL_BUILT_MODULE))

endif
