obj-m += avl6211_fe.o 

avl6211_fe-objs := avlfrontend.o \
                   AVL6211_API.o \

avl6211_fe-objs += src/avl.o \
                   src/avl_dvbsx.o \
                   src/ExtAV2011.o \
                   src/ExtSharpBS2S7HZ6306.o \
                   src/IBase.o \
                   src/IBlindScan.o \
                   src/IBlindscanAPI.o \
                   src/IBSP.o \
                   src/IDiseqc.o \
                   src/II2C.o \
                   src/II2CRepeater.o \
                   src/IRx.o \
                   src/ITuner.o \
